name: Update README

on:
  schedule:
    - cron: "* */1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: Readme-Workflows/recent-activity@d6a4e11a4a27b0e2d43063839a68bbb1e3fbe21c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
